config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'

  namespace :admin do
    root to: 'home#index'

    resources :financial_entries, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/arquivo.rb
class Arquivo < ApplicationRecord
  has_one_attached :documento

  validates :sha1, uniqueness: true
  validates :sha1, presence: true

  def sha1_from_tempfile(file)
    self.sha1 = Digest::SHA1.file(file.path)
    self
  end
end

app/models/beneficiario.rb
class Beneficiario < ApplicationRecord
end

app/models/cartao.rb
class Cartao < ApplicationRecord
end

app/models/credit_card.rb
# frozen_string_literal: true

class CreditCard < ApplicationRecord
  belongs_to :customer

  validates :number, presence: true
end

app/models/customer.rb
# frozen_string_literal: true

class Customer < ApplicationRecord
  has_many :credit_cards, dependent: :restrict_with_error
end

app/models/financial_entry.rb
# frozen_string_literal: true

class FinancialEntry < ApplicationRecord
  belongs_to :user

  validates :content_file, presence: true
end

app/models/loja.rb
class Loja < ApplicationRecord
  has_many :registros, dependent: :destroy

  def balance
    registros.map(&:value).sum
  end
end

app/models/registro.rb
class Registro < ApplicationRecord
  belongs_to :tipo_de_transacao
  belongs_to :beneficiario
  belongs_to :cartao
  belongs_to :loja
  belongs_to :arquivo

  def self.parser(parser)
    case parser
    when CnabParser::Version01
      parser_v01(parser)
    else
      raise_("Unsupporter parser #{parser.class}")
    end
  end

  def value
    valor * tipo_de_transacao.factor
  end

  class << self
    private

    def parser_v01(parser)
      new(parser.params)
    end
  end
end

app/models/store.rb
# frozen_string_literal: true

class Store < ApplicationRecord
  validates :name, presence: true
end

app/models/tipo_de_transacao.rb
class TipoDeTransacao < ApplicationRecord
  def factor
    sinal ? 1 : -1
  end
end

app/models/transaction.rb
# frozen_string_literal: true

class Transaction < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :credit_card
  belongs_to :store
  belongs_to :kind, class_name: 'TransactionKind'
  has_one :customer, through: :credit_card
end

app/models/transaction_kind.rb
# frozen_string_literal: true

class TransactionKind < ApplicationRecord
  has_enumeration_for :nature, with: TransactionKindNature, create_helpers: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  %i[uid email nome primeiro_nome sobrenome foto token].each do |attribute|
    validates attribute, presence: true
  end

  %i[uid email token].each do |uniq_attribute|
    validates uniq_attribute, uniqueness: true
  end

  def self.load_info(options = {})
    usuario = find_by(uid: options[:id])
    return usuario if usuario

    user_params = { uid: :id, email: :email, nome: :name, primeiro_nome: :given_name,
                    sobrenome: :family_name, foto: :picture, token: :access_token }
    opt = options.clone
    user_params.each { |k, v| opt[k] = opt[v] }
    create(opt.slice(*user_params.keys))
  end
end

app/controllers/auth_controller.rb
# frozen_string_literal: true

class AuthController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < AuthController
  def index
    @transactions = query.paginate(params[:page])
  end

  private

  def query
    @query ||= TransactionsQuery.new.by_user(current_user.id)
  end
end

app/controllers/lojas_controller.rb
class LojasController < ApplicationController
  before_action :set_loja, only: %i[show]

  def index
    @lojas = Loja.all
  end

  def show
    @loja = @loja.decorate
  end

  private

  def set_loja
    @loja = Loja.find(params[:id])
  end
end

app/controllers/sessao_controller.rb
class SessaoController < ApplicationController
  skip_before_action :current_user_authenticated, only: %i[entrar callback]

  def callback
    user = loader_user
    session[:user] = user.id
  rescue StandardError
    # try login with invalid params
  ensure
    redirect_to :root
  end

  def sair
    session.clear
    redirect_to :root
  end

  def entrar; end

  private

  def google_auth
    Api::Google.auth(code: params_callback, request: request)
  end

  def loader_user
    auth = google_auth
    info = Api::Google.info(auth)
    Usuario.load_info(info.deep_merge(auth))
  end

  def params_callback
    params.require(:code)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include ::Interage::ApplicationHelper

  # ::Interage::FlashMessageHelper
  ALIAS_TYPES = { notice: 'success', alert: 'info' }.freeze

  def handle_type(type)
    ALIAS_TYPES[type] || type
  end

  def translate_model_name(model, count = 1)
    model.model_name.human(count: count)
  end
  alias tm translate_model_name
end

app/views/layouts/admin/_app_links.html.erb
<div id="<%= whos_call_me %>-app-links">
  <a class="list-group-item" href="#<%= whos_call_me %>-current-user" data-toggle="collapse">
    <div class="d-flex justify-content-start align-items-center">
      <%= gravatar_image_tag(
            current_user.email,
            class: 'rounded-circle user-avatar img-thumbnail'
          ) %>

      <span class="menu-collapsed text-truncate"><%= current_user.name %></span>

      <%= app_icon('chevron-down', class: 'ml-auto') %>
    </div>
  </a>

  <div id="<%= whos_call_me %>-current-user"
       data-parent="#<%= whos_call_me %>-app-links"
       class="sidebar-submenu collapse">
    <%= aside_link_to '#' do %>
      <%= app_icon_text('cogs', t('.update_user')) %>
    <% end %>

    <%= aside_link_to '#' do %>
      <%= app_icon_text('key', t('.update_password')) %>
    <% end %>

    <%= aside_link_to destroy_user_session_path, method: :delete do %>
      <%= app_icon_text('sign-out', t('.sign_out')) %>
    <% end %>
  </div>

  <%= aside_link_to admin_root_path, class: 'list-group-item' do %>
    <%= app_icon_text('home', t('.go_to_home')) %>
  <% end %>

  <%= aside_link_to admin_root_path, class: 'item-large' do %>
    <%= app_icon_text('exchange', tmp(Transaction)) %>
    <%= bs_badge_danger('Beta') %>
  <% end %>

  <h6 class="sidebar-heading d-flex justify-content-between
             align-items-center px-3 mt-4 mb-1">
    <span>Relatótio do mês</span>
    <%= app_icon('plus') %>
  </h6>

  <%= aside_link_to admin_financial_entries_path do %>
    <%= app_icon_text('upload', tmp(FinancialEntry)) %>
  <% end %>
</div>

app/views/layouts/admin/_modal_app_links.html.erb
<div class="modal fade" id="modal-application-links" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h6 class="modal-title" id="modal-application-links-label">
          <%= app_name %>
        </h6>

        <button type="button" title="fechar" class="close" data-dismiss="modal">
          <%= app_icon('times') %>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'layouts/admin/app_links', whos_call_me: 'modal' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/admin/_navbar.html.erb
<%= link_to admin_root_path, title: app_text_version,
                             class: 'navbar-brand col-sm-4 col-md-3 col-lg-2
                                     mr-0 text-truncate' do %>
  <%= app_name %>
<% end %>

<div id="hambuger-menu" class="mr-auto float-left">
  <%= image_tag 'logo.png', class: 'img-thumbnail' %>
  <%= link_to_modal app_icon('bars'), '#modal-application-links',
                    class: 'btn btn-sm btn-outline-application d-sm-none' %>
</div>

<div class="navbar-nav px-3">
  <ul class="nav ">
    <li class="nav-item">
      <%= link_to destroy_user_session_path, class: 'nav-link',
                                             method: :delete do %>
        <%= app_icon_text('sign-out', t('.sign_out')) %>
      <% end %>
    </li>
  </ul>
</div>

app/views/layouts/admin/_sidebar.html.erb
<div id="sidebar-container" class="sidebar-sticky d-none d-sm-block">
  <%= render 'layouts/admin/app_links', whos_call_me: 'sidebar' %>

  <div class="list-group-item-logo">
    <%= image_tag 'icons/apple-touch-icon.png',
                  class: 'rounded', title: app_text_version %>
  </div>
</div>

app/views/shared/_body_page_title.html.erb
<% content_for(:page_title, page_title) %>

<% content_for :body_page_title do %>
  <div id="body-page-title" class="row">
    <div class="col-<%= defined?(link) ? '6 col-sm-5 col-md-8 col-lg-9' : 12 %>">
      <h1 class="h5 text-truncate" title="<%= strip_tags page_title %>">
        <%= page_title %>
      </h1>
    </div>

    <% if defined?(link) %>
      <div class="col-6 col-sm-7 col-md-4 col-lg-3 text-right">
        <%= link %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_edit_title.html.erb
<%= render 'shared/body_page_title',
           page_title: t('.title', model: tm(resource)) %>

app/views/shared/_flash_messages.html.erb
<% if success = flash[:success] %>
  <div class="alert alert-success"><%= success %></div>
<% elsif error = flash[:error] %>
  <div class="alert alert-danger"><%= error %></div>
<% elsif info = flash[:info] %>
  <div class="alert alert-info"><%= info %></div>
<% elsif warning = flash[:warning] %>
  <div class="alert alert-warning"><%= warning %></div>
<% end %>

app/views/shared/_form_actions.html.erb
<div class="text-right mt-4">
  <%= link_to_back(back_url || :back) %>

  <%= f.submit class: 'btn btn-primary' %>
</div>

app/views/shared/_index_title.html.erb
<%= render 'shared/body_page_title',
           page_title: t('.title', model: tmp(resource)) %>

app/views/shared/_index_title_add.html.erb
<%= render 'shared/body_page_title',
           page_title: t('.title', model: tmp(resource)),
           link: link_to_new(resource, url) %>

app/views/shared/_messages_errors.html.erb
<% if resource.errors.full_messages.any? %>
  <div class="alert alert-danger">
    <h4>Ocorreu um problema</h4>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li>* <%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_new_title.html.erb
<%= render 'shared/body_page_title',
           page_title: t('.title', model: tm(resource)) %>

app/views/shared/_show_title.html.erb
<%= render 'shared/body_page_title',
           page_title: t(".title.#{gender}", model: tm(resource)) %>

app/views/transactions/_index.html.erb
<% if transactions.empty? %>
  <%= bs_alert_info('Nenhuma transação foi encontrada') %>
<% else %>
  <div class="card">
    <div class="card-body">
      <div class="card-text">
        <table class="mb-0 table table-hover">
          <thead class="thead-light">
            <tr>
              <% if defined?(show_user) %>
                <th><%= ta(Transaction, :user) %></th>
              <% end %>
              <th><%= ta(Transaction, :kind) %></th>
              <th><%= ta(Transaction, :store) %></th>
              <th><%= ta(Transaction, :amount) %></th>
              <th><%= ta(Transaction, :customer) %></th>
              <th><%= ta(Transaction, :occurred_at) %></th>
            </tr>
          </thead>
          <tbody>
            <% transactions.each do |transaction| %>
              <tr>
                <% if defined?(show_user) %>
                  <td><%= transaction.user_name %></td>
                <% end %>
                <td>
                  <div><%= transaction.kind_description %></div>
                  <small><%= transaction.kind_nature_humanize %></small>
                </td>
                <td>
                  <div><%= transaction.store_name %></div>
                  <small><%= transaction.store_responsible_name %></small>
                </td>
                <td>
                  <div><%= transaction.formatted_amount %></div>
                  <small><%= transaction.credit_card_number %></small>
                </td>
                <td><%= transaction.customer_ssn %></td>
                <td><%= transaction.occurred_date %></td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <%= pagination_links(transactions) %>
      </div>
    </div>
  </div>
<% end %>