config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'

  namespace :admin do
    root to: 'home#index'

    resources :financial_entries, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/arquivo.rb
class Arquivo < ApplicationRecord
  has_one_attached :documento

  validates :sha1, uniqueness: true
  validates :sha1, presence: true

  def sha1_from_tempfile(file)
    self.sha1 = Digest::SHA1.file(file.path)
    self
  end
end

app/models/beneficiario.rb
class Beneficiario < ApplicationRecord
end

app/models/cartao.rb
class Cartao < ApplicationRecord
end

app/models/credit_card.rb
# frozen_string_literal: true

class CreditCard < ApplicationRecord
  belongs_to :customer

  validates :number, presence: true
end

app/models/customer.rb
# frozen_string_literal: true

class Customer < ApplicationRecord
  has_many :credit_cards, dependent: :restrict_with_error
end

app/models/financial_entry.rb
# frozen_string_literal: true

class FinancialEntry < ApplicationRecord
  belongs_to :user

  validates :content_file, presence: true
end

app/models/loja.rb
class Loja < ApplicationRecord
  has_many :registros, dependent: :destroy

  def balance
    registros.map(&:value).sum
  end
end

app/models/registro.rb
class Registro < ApplicationRecord
  belongs_to :tipo_de_transacao
  belongs_to :beneficiario
  belongs_to :cartao
  belongs_to :loja
  belongs_to :arquivo

  def self.parser(parser)
    case parser
    when CnabParser::Version01
      parser_v01(parser)
    else
      raise_("Unsupporter parser #{parser.class}")
    end
  end

  def value
    valor * tipo_de_transacao.factor
  end

  class << self
    private

    def parser_v01(parser)
      new(parser.params)
    end
  end
end

app/models/store.rb
# frozen_string_literal: true

class Store < ApplicationRecord
  validates :name, presence: true
end

app/models/tipo_de_transacao.rb
class TipoDeTransacao < ApplicationRecord
  def factor
    sinal ? 1 : -1
  end
end

app/models/transaction.rb
# frozen_string_literal: true

class Transaction < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :credit_card
  belongs_to :store
  belongs_to :kind, class_name: 'TransactionKind'
  has_one :customer, through: :credit_card
end

app/models/transaction_kind.rb
# frozen_string_literal: true

class TransactionKind < ApplicationRecord
  has_enumeration_for :nature, with: TransactionKindNature, create_helpers: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  %i[uid email nome primeiro_nome sobrenome foto token].each do |attribute|
    validates attribute, presence: true
  end

  %i[uid email token].each do |uniq_attribute|
    validates uniq_attribute, uniqueness: true
  end

  def self.load_info(options = {})
    usuario = find_by(uid: options[:id])
    return usuario if usuario

    user_params = { uid: :id, email: :email, nome: :name, primeiro_nome: :given_name,
                    sobrenome: :family_name, foto: :picture, token: :access_token }
    opt = options.clone
    user_params.each { |k, v| opt[k] = opt[v] }
    create(opt.slice(*user_params.keys))
  end
end

app/controllers/admin/financial_entries_controller.rb
# frozen_string_literal: true

module Admin
  class FinancialEntriesController < ::Admin::BaseController
    def index
      @financial_entries = query.paginate(params[:page])
    end

    def new
      @financial_entry = query.build
    end

    def create
      service = ImportCNBAFileService.call(financial_entry_params)

      if service.success?
        flash[:success] = t('controllers.create.success')

        redirect_to admin_root_path
      else
        @financial_entry = service.financial_entry
        render :new
      end
    end

    private

    def query
      @query ||= FinancialEntriesQuery.new
    end

    def financial_entry_params
      params.require(:financial_entry)
            .permit(:user_id)
            .merge(content_file: content_file)
    end

    def content_file
      return if tempfile.blank?

      File.open(tempfile).read
    end

    def tempfile
      params.dig(:financial_entry, :content_file)&.tempfile
    end
  end
end

app/controllers/auth_controller.rb
# frozen_string_literal: true

class AuthController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/financial_entries_controller.rb
class FinancialEntriesController < ApplicationController
  # DELETE /financial_entries/1
  # DELETE /financial_entries/1.json
  def destroy
    deleted_record = Command::FinancialEntry::Destroy.new(id: params[:id]).execute

    respond_to do |format|
      format.html { redirect_to edit_store_path(deleted_record.store_id), notice: 'Financial entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /financial_entries/import
  def import_form
    render :import
  end

  # POST /financial_entries/import
  def import
    count = Command::FinancialEntry::Import.new(file: entry_import_params[:file]).execute

    respond_to do |format|
      format.html { redirect_to import_financial_entries_path, notice: "#{count} financial entries successfully imported." }
      format.json { head :ok }
    end
  end

  private
    def entry_import_params
      params.require(:upload).permit(:file)
    end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < AuthController
  def index
    @transactions = query.paginate(params[:page])
  end

  private

  def query
    @query ||= TransactionsQuery.new.by_user(current_user.id)
  end
end

app/controllers/lojas_controller.rb
class LojasController < ApplicationController
  before_action :set_loja, only: %i[show]

  def index
    @lojas = Loja.all
  end

  def show
    @loja = @loja.decorate
  end

  private

  def set_loja
    @loja = Loja.find(params[:id])
  end
end

app/controllers/sessao_controller.rb
class SessaoController < ApplicationController
  skip_before_action :current_user_authenticated, only: %i[entrar callback]

  def callback
    user = loader_user
    session[:user] = user.id
  rescue StandardError
    # try login with invalid params
  ensure
    redirect_to :root
  end

  def sair
    session.clear
    redirect_to :root
  end

  def entrar; end

  private

  def google_auth
    Api::Google.auth(code: params_callback, request: request)
  end

  def loader_user
    auth = google_auth
    info = Api::Google.info(auth)
    Usuario.load_info(info.deep_merge(auth))
  end

  def params_callback
    params.require(:code)
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  # GET /stores
  # GET /stores.json
  def index
    @stores = Command::Store::Search.new.execute
  end

  # GET /stores/1/edit
  def edit
    @store = Command::Store::Show.new(id: params[:id]).execute
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      @store = Command::Store::Update.new(id: params[:id], changes: store_params).execute

      if @store.update(store_params)
        format.html { redirect_to edit_store_path(@store.id), notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @deleted_store = Command::Store::Destroy.new(id: params[:id]).execute

    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Only allow a list of trusted parameters through.
    def store_params
      params.require(:store).permit(:name, :owner)
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include ::Interage::ApplicationHelper

  # ::Interage::FlashMessageHelper
  ALIAS_TYPES = { notice: 'success', alert: 'info' }.freeze

  def handle_type(type)
    ALIAS_TYPES[type] || type
  end

  def translate_model_name(model, count = 1)
    model.model_name.human(count: count)
  end
  alias tm translate_model_name
end

app/views/admin/financial_entries/_form.html.erb
<%= simple_form_for [:admin, @financial_entry] do |f| %>
  <div class="card mb-3">
    <div class="card-header">Importar arquivo</div>
    <div class="card-body">
      <div class="row">
        <div class="col-md-6">
          <%= f.association :user %>
        </div>

        <div class="col-md-6">
          <%= f.input :content_file, as: :file %>
        </div>
      </div>

    </div>
  </div>

  <%= render 'shared/form_actions', f: f, back_url: back_url %>
<% end %>

app/views/admin/financial_entries/index.html.erb
<%= render 'shared/index_title_add', resource: FinancialEntry,
                                     url: new_admin_financial_entry_path %>

<% if @financial_entries.empty? %>
  <%= bs_alert_info('Nenhuma transação foi encontrada') %>
<% else %>
  <div class="card">
    <div class="card-body">
      <div class="card-text">
        <table class="mb-0 table table-hover">
          <thead class="thead-light">
            <tr>
              <th><%= tmp(FinancialEntry) %></th>
            </tr>
          </thead>
          <tbody>
            <% @financial_entries.each do |entry| %>
              <tr>
                <td>
                  <div class="mb-2"><%= entry.user_name.presence %></div>
                  <div><code><%= entry.content_file %></code></div>
                  <small><%= entry.created_date %></small>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <%= pagination_links(@financial_entries) %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/financial_entries/new.html.erb
<%= render 'shared/new_title', resource: Transaction %>

<%= render 'form', back_url: admin_root_path %>

app/views/financial_entries/_index_table.haml
- model_class = FinancialEntry

%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:kind)
      %th= model_class.human_attribute_name(:transaction_date)
      %th= model_class.human_attribute_name(:transaction_time)
      %th= model_class.human_attribute_name(:amount)
      %th= model_class.human_attribute_name(:social_number)
      %th= model_class.human_attribute_name(:card_number)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - entries.each do |financial_entry|
      %tr
        %td= link_to financial_entry.id, financial_entry_path(financial_entry)
        %td= financial_entry.kind
        %td= financial_entry.transaction_date
        %td= financial_entry.transaction_time
        %td= financial_entry.amount
        %td= financial_entry.social_number
        %td= financial_entry.card_number
        %td
          = link_to t('.destroy', :default => t("helpers.links.destroy")), financial_entry_path(financial_entry), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

app/views/financial_entries/import.haml
.page-header
  %h1 Import financial entries

= form_for :upload, html: { multipart: true, url: import_financial_entries_path, class: "form form-horizontal financial_entry" } do |f|
  .form-group
    = f.label :file, class: 'control-label col-lg-1'
    .col-lg-10
      = f.file_field :file, class: 'form-control', required: true, accept: Mime[:text]
    = f.error_span(:file)
  .form-group
    .col-lg-offset-1.col-lg-10
      = f.submit 'Upload' ,class: 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), stores_path, :class => 'btn btn-default'

app/views/financial_entries/index.html.haml
- model_class = FinancialEntry
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize

= render :partial => "financial_entries/index_table", locals: { entries: @financial_entries }
= link_to t('.new', :default => t("helpers.links.new")), new_financial_entry_path, :class => 'btn btn-primary'